version: '3'

vars:
  DATABASE_URL: postgresql://user:password@localhost:5432/myapp?sslmode=disable

tasks:
  build:
    cmds:
      - go build -o bin/server ./cmd/server

  run:
    cmds:
      - go run ./cmd/server/main.go

  test:unit:
    cmds:
      - go test -v ./... -run Unit

  test:integration:
    cmds:
      - go test -v ./... -run Integration

  lint:
    cmds:
      - golangci-lint run

  generate:sqlc:
    cmds:
      - sqlc generate

  generate:openapi:
    cmds:
      - mkdir -p pkg/api
      - oapi-codegen -package api openapi.yml > api/server.gen.go

  migrate:up:
    cmds:
      - migrate -path db/migration -database "{{.DATABASE_URL}}" up

  migrate:down:
    cmds:
      - migrate -path db/migration -database "{{.DATABASE_URL}}" down

  migrate:create:
    cmds:
      - migrate create -ext sql -dir db/migration -seq {{.CLI_ARGS}}

  docker:up:
    cmds:
      - docker-compose up -d

  docker:down:
    cmds:
      - docker-compose down
